[package]
name = "taiga-bot-rs"
version = "4.2.0"
authors = ["Chehui Chou <deadshot465@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = ">=1.0.57"
base64 = ">=0.13.0"
chrono = { version = ">=0.4", features = ["serde"] }
env_logger = ">=0.9.0"
image = ">=0.24.2"
log = ">=0.4"
once_cell = ">=1.12.0"
owoify_rs = ">=1.0.0"
rand = ">=0.8.5"
regex = ">=1"
reqwest = { version = ">=0.11", features = ["blocking", "json"] }
serde = { version = ">=1.0", features = ["derive"] }
serde_json = ">=1.0"
serenity = { version = ">=0.11.2", features = ["cache", "collector", "gateway", "unstable_discord_api"] }
tokio = { version = ">=1.19.2", features = ["full", "parking_lot"] }
toml = ">=0.5.9"

[profile.dev]
split-debuginfo = "unpacked"
