[package]
name = "taiga-bot-rs"
version = "0.1.0"
authors = ["Chehui Chou <deadshot465@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
env_logger = "0.7.1"
lazy_static = "1.4.0"
log = "0.4"
owoify_rs = "0.1.3"
rand = "0.7.3"
regex = "1"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serenity = { git = "https://github.com/acdenisSK/serenity", branch = "await_next", features = ["cache", "collector", "gateway"] }
tokio = { version = "0.2", features = ["full"] }