[package]
name = "taiga-bot-rs"
version = "3.1.0"
authors = ["Chehui Chou <deadshot465@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = ">=1.0.33"
chrono = { version = ">=0.4", features = ["serde"] }
dotenv = ">=0.15.0"
dotenv_codegen = ">=0.15.0"
env_logger = ">=0.7.1"
lazy_static = ">=1.4.0"
log = ">=0.4"
once_cell = ">=1.5.2"
owoify_rs = ">=0.1.3"
prost = ">=0.6.1"
rand = ">=0.7.3"
regex = ">=1"
reqwest = { version = ">=0.10", features = ["blocking", "json"] }
serde = { version = ">=1.0", features = ["derive"] }
serde_json = ">=1.0"
serenity = { version = ">=0.9.0-rc.2", features = ["cache", "collector", "gateway"] }
tokio = { version = ">=0.2", features = ["full"] }
tonic = ">=0.3.1"

[build-dependencies]
tonic-build = ">=0.3.1"
